# Generated by Django 5.0.1 on 2024-01-15 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_categories_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='text',
        ),
    ]
