# Generated by Django 5.0.1 on 2024-01-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_article_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title2',
            field=models.CharField(default=1, max_length=212),
            preserve_default=False,
        ),
    ]
